
require './libs/setup'
expect = require('chai').expect
userLib = require './libs/user'
userLib.createHooks {}
request = require('supertest')
tcc = require '../server/services/tcc'

cardNumber = null
testCard = null

describe 'TCC API', ->

	@timeout 15000


	it 'should create a new card using svAlloc', (done) ->
		TCC.createCard(10, '183').then((card) ->
			console.log 'new card created:', card
			cardNumber = card.card_number
			testCard = card
			done()
			return
		).fail (err) ->
			console.log 'card creation failed with error:', err

			done err
			return
		return

	it 'should query card data from tcc', (done) ->
		#cardNumber = '2073183100123127'
		TCC.cardInfo(testCard).then((tcc_card) ->
			console.log 'got card: ', tcc_card
			expect(tcc_card.balance).to.equal('10.00')
			done()
			return
		).fail (err) ->
			done err
			return
		return

	it 'should redeem some value from tcc', (done) ->
		TCC.redeemCard(cardNumber, 1.50).then((tcc_card) ->
			console.log 'got redeemed card: ', tcc_card
			expect(tcc_card.balance).to.equal('8.50')
			done()
			return
		).fail (err) ->
			done err
			return
		return





	

# ---
# generated by js2coffee 2.0.1