ConnectRoles = require('connect-roles');


module.exports = (app) ->

	user = new ConnectRoles(
		failureHandler: (req, res, action) ->
	  # optional function to customise code that runs when
	  # user fails authorisation
	  	res.send(403, 'Access Denied - You don\'t have permission to: ' + action)

	  async: true
	)

# ---
# generated by js2coffee 2.0.0